-- AlterTable
ALTER TABLE "Competition" ADD COLUMN     "standingsTieBreakers" JSONB NOT NULL DEFAULT '["POINTS","GOAL_DIFFERENCE","GOALS_FOR","HEAD_TO_HEAD_POINTS","HEAD_TO_HEAD_GOAL_DIFFERENCE","HEAD_TO_HEAD_GOALS_FOR","FAIR_PLAY","DRAWING_OF_LOTS"]';
